# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Teh blog
tagline:             'tis a blog'
description:         'tis a description of a blog'
url:                 http://s0lst1c3.github.io
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Author here
  url:               https://twitter.com/s0lst1c3
  email:             contact@solstice.me

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/s0lst1c3
twitter:			http://twitter.com/s0lst1c3

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
