# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               s0lst1ce.github.io
tagline:             ''
description:         "My name is John Gabriel Ryan. I'm an aspiring offensive security R&D, and this is my blog."
url:                 http://s0lst1ce.github.io
baseurl:             /
paginate:            7

# About/contact
author:
  name:              John Gabriel 's0lst1ce' Ryan
  url:               https://twitter.com/s0lst1c3
  email:             john.ryan@ogsystems.com

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/s0lst1ce
twitter:			http://twitter.com/s0lst1ce

